### PR TITLE
Fix autogen.sh for Mac OSX w/ homebrew

### PR DESCRIPTION
**Pull request by nikreiman**

### CODE REVIEW

**Comment by bfontaine** [comment]
This assumes *all* OSX users have Homebrew, which is not the case. This is more an issue with Homebrew itself than this library.

If you really wanted to make it work you could try something like:

```sh
LIBTOOL=libtool

# …

if [ "$(which glibtool)" ]; then
    LIBTOOL=glibtool
fi

# then use $LIBTOOL instead of libtool
```

**Comment by nikreiman** [comment]
@bfontaine you're right, that's a good point. However, there are cases where one might want to build audiofile with sources outside of homebrew, but using homebrew tools (that is, when audiofile is a source dependency of another project). Also this commit would allow you to remove the `inreplace "autogen.sh", "libtool", "glibtool"` line from your brew formula. :)

I have amended the PR and added an extra check for `which glibtool`. But if you don't want this change in audiofile, I can understand and wouldn't mind abandoning this commit.

**Comment by bfontaine** [comment]
@nikreiman I’m not a maintainer of this project :)

**Comment by mpruett** [comment]
Thanks for noting this issue. I've simplified autopen.sh to call autoreconf, so this change is no longer necessary.

**Pull request closed without merging**
